version: 2
jobs:
  build:
    steps:
      -run: 
         echo 'sdfksdfnkl'
    



commands:
  sayhello:
    description: "A very simple command for demonstration purposes"
    parameters:
      to:
        type: string
        default: "Hello World"
    steps:
      - run: echo << parameters.to >>