version: 2
jobs:
build:
docker:
- image: circleci/ruby:2.5.5-node-browsers
environment:
DATABASE_URL: 'postgres://user@localhost:5432/user_test'
RAILS_ENV: test

- image: circleci/postgres:10.3-alpine
environment:
POSTGRES_USER: user
POSTGRES_DB: user_test
working_directory: ~/repo
